/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BilheteriaRouteImport } from './routes/bilheteria'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminEquipeRouteImport } from './routes/admin.equipe'
import { Route as BilheteriaIndexRouteImport } from './routes/bilheteria.index'
import { Route as BilheteriaAvulsaRouteImport } from './routes/bilheteria.avulsa'
import { Route as BilheteriaCaixaRouteImport } from './routes/bilheteria.caixa'
import { Route as BilheteriaImpressaoRouteImport } from './routes/bilheteria.impressao'
import { Route as BilheteriaRetiradaRouteImport } from './routes/bilheteria.retirada'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as FCodigoRouteImport } from './routes/f.$codigo'
import { Route as PAcessoRouteImport } from './routes/p.$acesso'
import { Route as TermosSlugRouteImport } from './routes/termos.$slug'
import { Route as AdminEventosIndexRouteImport } from './routes/admin.eventos.index'
import { Route as AdminEventosEventoIdRouteImport } from './routes/admin.eventos.$eventoId'
import { Route as AdminLocaisIndexRouteImport } from './routes/admin.locais.index'
import { Route as BilheteriaFamiliaFamiliaIdRouteImport } from './routes/bilheteria.familia.$familiaId'
import { Route as ESlugIndexRouteImport } from './routes/e.$slug.index'
import { Route as ESlugSessaoIdRouteImport } from './routes/e.$slug.$sessaoId'
import { Route as FCodigoIndexRouteImport } from './routes/f.$codigo.index'
import { Route as FCodigoSessaoIdRouteImport } from './routes/f.$codigo.$sessaoId'
import { Route as AdminEventosEventoIdIndexRouteImport } from './routes/admin.eventos.$eventoId.index'
import { Route as AdminEventosEventoIdAdicionaisRouteImport } from './routes/admin.eventos.$eventoId.adicionais'
import { Route as AdminEventosEventoIdConteudosRouteImport } from './routes/admin.eventos.$eventoId.conteudos'
import { Route as AdminEventosEventoIdElencoRouteImport } from './routes/admin.eventos.$eventoId.elenco'
import { Route as AdminEventosEventoIdEnvioRouteImport } from './routes/admin.eventos.$eventoId.envio'
import { Route as AdminEventosEventoIdPrecosRouteImport } from './routes/admin.eventos.$eventoId.precos'
import { Route as AdminEventosEventoIdSessoesRouteImport } from './routes/admin.eventos.$eventoId.sessoes'
import { Route as AdminEventosEventoIdVisaoGeralRouteImport } from './routes/admin.eventos.$eventoId.visao-geral'
import { Route as ApiPagarmeWebhookSegredoRouteImport } from './routes/api/pagarme/webhook.$segredo'
import { Route as FCodigoPagamentoAcessoRouteImport } from './routes/f.$codigo.pagamento.$acesso'
import { Route as FCodigoPedidoAcessoRouteImport } from './routes/f.$codigo.pedido.$acesso'
import { Route as AdminLocaisLocalIdMapasMapaIdRouteImport } from './routes/admin.locais.$localId.mapas.$mapaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BilheteriaRoute = BilheteriaRouteImport.update({
  id: '/bilheteria',
  path: '/bilheteria',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipeRoute = AdminEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdminRoute,
} as any)
const BilheteriaIndexRoute = BilheteriaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BilheteriaRoute,
} as any)
const BilheteriaAvulsaRoute = BilheteriaAvulsaRouteImport.update({
  id: '/avulsa',
  path: '/avulsa',
  getParentRoute: () => BilheteriaRoute,
} as any)
const BilheteriaCaixaRoute = BilheteriaCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => BilheteriaRoute,
} as any)
const BilheteriaImpressaoRoute = BilheteriaImpressaoRouteImport.update({
  id: '/impressao',
  path: '/impressao',
  getParentRoute: () => BilheteriaRoute,
} as any)
const BilheteriaRetiradaRoute = BilheteriaRetiradaRouteImport.update({
  id: '/retirada',
  path: '/retirada',
  getParentRoute: () => BilheteriaRoute,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FCodigoRoute = FCodigoRouteImport.update({
  id: '/f/$codigo',
  path: '/f/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const PAcessoRoute = PAcessoRouteImport.update({
  id: '/p/$acesso',
  path: '/p/$acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosSlugRoute = TermosSlugRouteImport.update({
  id: '/termos/$slug',
  path: '/termos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventosIndexRoute = AdminEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosEventoIdRoute = AdminEventosEventoIdRouteImport.update({
  id: '/eventos/$eventoId',
  path: '/eventos/$eventoId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocaisIndexRoute = AdminLocaisIndexRouteImport.update({
  id: '/locais/',
  path: '/locais/',
  getParentRoute: () => AdminRoute,
} as any)
const BilheteriaFamiliaFamiliaIdRoute =
  BilheteriaFamiliaFamiliaIdRouteImport.update({
    id: '/familia/$familiaId',
    path: '/familia/$familiaId',
    getParentRoute: () => BilheteriaRoute,
  } as any)
const ESlugIndexRoute = ESlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ESlugRoute,
} as any)
const ESlugSessaoIdRoute = ESlugSessaoIdRouteImport.update({
  id: '/$sessaoId',
  path: '/$sessaoId',
  getParentRoute: () => ESlugRoute,
} as any)
const FCodigoIndexRoute = FCodigoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FCodigoRoute,
} as any)
const FCodigoSessaoIdRoute = FCodigoSessaoIdRouteImport.update({
  id: '/$sessaoId',
  path: '/$sessaoId',
  getParentRoute: () => FCodigoRoute,
} as any)
const AdminEventosEventoIdIndexRoute =
  AdminEventosEventoIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const AdminEventosEventoIdAdicionaisRoute =
  AdminEventosEventoIdAdicionaisRouteImport.update({
    id: '/adicionais',
    path: '/adicionais',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const AdminEventosEventoIdConteudosRoute =
  AdminEventosEventoIdConteudosRouteImport.update({
    id: '/conteudos',
    path: '/conteudos',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const AdminEventosEventoIdElencoRoute =
  AdminEventosEventoIdElencoRouteImport.update({
    id: '/elenco',
    path: '/elenco',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const AdminEventosEventoIdEnvioRoute =
  AdminEventosEventoIdEnvioRouteImport.update({
    id: '/envio',
    path: '/envio',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const AdminEventosEventoIdPrecosRoute =
  AdminEventosEventoIdPrecosRouteImport.update({
    id: '/precos',
    path: '/precos',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const AdminEventosEventoIdSessoesRoute =
  AdminEventosEventoIdSessoesRouteImport.update({
    id: '/sessoes',
    path: '/sessoes',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const AdminEventosEventoIdVisaoGeralRoute =
  AdminEventosEventoIdVisaoGeralRouteImport.update({
    id: '/visao-geral',
    path: '/visao-geral',
    getParentRoute: () => AdminEventosEventoIdRoute,
  } as any)
const ApiPagarmeWebhookSegredoRoute =
  ApiPagarmeWebhookSegredoRouteImport.update({
    id: '/api/pagarme/webhook/$segredo',
    path: '/api/pagarme/webhook/$segredo',
    getParentRoute: () => rootRouteImport,
  } as any)
const FCodigoPagamentoAcessoRoute = FCodigoPagamentoAcessoRouteImport.update({
  id: '/pagamento/$acesso',
  path: '/pagamento/$acesso',
  getParentRoute: () => FCodigoRoute,
} as any)
const FCodigoPedidoAcessoRoute = FCodigoPedidoAcessoRouteImport.update({
  id: '/pedido/$acesso',
  path: '/pedido/$acesso',
  getParentRoute: () => FCodigoRoute,
} as any)
const AdminLocaisLocalIdMapasMapaIdRoute =
  AdminLocaisLocalIdMapasMapaIdRouteImport.update({
    id: '/locais/$localId/mapas/$mapaId',
    path: '/locais/$localId/mapas/$mapaId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bilheteria': typeof BilheteriaRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/bilheteria/avulsa': typeof BilheteriaAvulsaRoute
  '/bilheteria/caixa': typeof BilheteriaCaixaRoute
  '/bilheteria/impressao': typeof BilheteriaImpressaoRoute
  '/bilheteria/retirada': typeof BilheteriaRetiradaRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/f/$codigo': typeof FCodigoRouteWithChildren
  '/p/$acesso': typeof PAcessoRoute
  '/termos/$slug': typeof TermosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bilheteria/': typeof BilheteriaIndexRoute
  '/admin/eventos/$eventoId': typeof AdminEventosEventoIdRouteWithChildren
  '/bilheteria/familia/$familiaId': typeof BilheteriaFamiliaFamiliaIdRoute
  '/e/$slug/$sessaoId': typeof ESlugSessaoIdRoute
  '/f/$codigo/$sessaoId': typeof FCodigoSessaoIdRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/locais/': typeof AdminLocaisIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/f/$codigo/': typeof FCodigoIndexRoute
  '/admin/eventos/$eventoId/adicionais': typeof AdminEventosEventoIdAdicionaisRoute
  '/admin/eventos/$eventoId/conteudos': typeof AdminEventosEventoIdConteudosRoute
  '/admin/eventos/$eventoId/elenco': typeof AdminEventosEventoIdElencoRoute
  '/admin/eventos/$eventoId/envio': typeof AdminEventosEventoIdEnvioRoute
  '/admin/eventos/$eventoId/precos': typeof AdminEventosEventoIdPrecosRoute
  '/admin/eventos/$eventoId/sessoes': typeof AdminEventosEventoIdSessoesRoute
  '/admin/eventos/$eventoId/visao-geral': typeof AdminEventosEventoIdVisaoGeralRoute
  '/api/pagarme/webhook/$segredo': typeof ApiPagarmeWebhookSegredoRoute
  '/f/$codigo/pagamento/$acesso': typeof FCodigoPagamentoAcessoRoute
  '/f/$codigo/pedido/$acesso': typeof FCodigoPedidoAcessoRoute
  '/admin/eventos/$eventoId/': typeof AdminEventosEventoIdIndexRoute
  '/admin/locais/$localId/mapas/$mapaId': typeof AdminLocaisLocalIdMapasMapaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/bilheteria/avulsa': typeof BilheteriaAvulsaRoute
  '/bilheteria/caixa': typeof BilheteriaCaixaRoute
  '/bilheteria/impressao': typeof BilheteriaImpressaoRoute
  '/bilheteria/retirada': typeof BilheteriaRetiradaRoute
  '/p/$acesso': typeof PAcessoRoute
  '/termos/$slug': typeof TermosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/bilheteria': typeof BilheteriaIndexRoute
  '/bilheteria/familia/$familiaId': typeof BilheteriaFamiliaFamiliaIdRoute
  '/e/$slug/$sessaoId': typeof ESlugSessaoIdRoute
  '/f/$codigo/$sessaoId': typeof FCodigoSessaoIdRoute
  '/admin/eventos': typeof AdminEventosIndexRoute
  '/admin/locais': typeof AdminLocaisIndexRoute
  '/e/$slug': typeof ESlugIndexRoute
  '/f/$codigo': typeof FCodigoIndexRoute
  '/admin/eventos/$eventoId/adicionais': typeof AdminEventosEventoIdAdicionaisRoute
  '/admin/eventos/$eventoId/conteudos': typeof AdminEventosEventoIdConteudosRoute
  '/admin/eventos/$eventoId/elenco': typeof AdminEventosEventoIdElencoRoute
  '/admin/eventos/$eventoId/envio': typeof AdminEventosEventoIdEnvioRoute
  '/admin/eventos/$eventoId/precos': typeof AdminEventosEventoIdPrecosRoute
  '/admin/eventos/$eventoId/sessoes': typeof AdminEventosEventoIdSessoesRoute
  '/admin/eventos/$eventoId/visao-geral': typeof AdminEventosEventoIdVisaoGeralRoute
  '/api/pagarme/webhook/$segredo': typeof ApiPagarmeWebhookSegredoRoute
  '/f/$codigo/pagamento/$acesso': typeof FCodigoPagamentoAcessoRoute
  '/f/$codigo/pedido/$acesso': typeof FCodigoPedidoAcessoRoute
  '/admin/eventos/$eventoId': typeof AdminEventosEventoIdIndexRoute
  '/admin/locais/$localId/mapas/$mapaId': typeof AdminLocaisLocalIdMapasMapaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bilheteria': typeof BilheteriaRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/equipe': typeof AdminEquipeRoute
  '/bilheteria/avulsa': typeof BilheteriaAvulsaRoute
  '/bilheteria/caixa': typeof BilheteriaCaixaRoute
  '/bilheteria/impressao': typeof BilheteriaImpressaoRoute
  '/bilheteria/retirada': typeof BilheteriaRetiradaRoute
  '/e/$slug': typeof ESlugRouteWithChildren
  '/f/$codigo': typeof FCodigoRouteWithChildren
  '/p/$acesso': typeof PAcessoRoute
  '/termos/$slug': typeof TermosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bilheteria/': typeof BilheteriaIndexRoute
  '/admin/eventos/$eventoId': typeof AdminEventosEventoIdRouteWithChildren
  '/bilheteria/familia/$familiaId': typeof BilheteriaFamiliaFamiliaIdRoute
  '/e/$slug/$sessaoId': typeof ESlugSessaoIdRoute
  '/f/$codigo/$sessaoId': typeof FCodigoSessaoIdRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/locais/': typeof AdminLocaisIndexRoute
  '/e/$slug/': typeof ESlugIndexRoute
  '/f/$codigo/': typeof FCodigoIndexRoute
  '/admin/eventos/$eventoId/adicionais': typeof AdminEventosEventoIdAdicionaisRoute
  '/admin/eventos/$eventoId/conteudos': typeof AdminEventosEventoIdConteudosRoute
  '/admin/eventos/$eventoId/elenco': typeof AdminEventosEventoIdElencoRoute
  '/admin/eventos/$eventoId/envio': typeof AdminEventosEventoIdEnvioRoute
  '/admin/eventos/$eventoId/precos': typeof AdminEventosEventoIdPrecosRoute
  '/admin/eventos/$eventoId/sessoes': typeof AdminEventosEventoIdSessoesRoute
  '/admin/eventos/$eventoId/visao-geral': typeof AdminEventosEventoIdVisaoGeralRoute
  '/api/pagarme/webhook/$segredo': typeof ApiPagarmeWebhookSegredoRoute
  '/f/$codigo/pagamento/$acesso': typeof FCodigoPagamentoAcessoRoute
  '/f/$codigo/pedido/$acesso': typeof FCodigoPedidoAcessoRoute
  '/admin/eventos/$eventoId/': typeof AdminEventosEventoIdIndexRoute
  '/admin/locais/$localId/mapas/$mapaId': typeof AdminLocaisLocalIdMapasMapaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bilheteria'
    | '/entrar'
    | '/privacidade'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/bilheteria/avulsa'
    | '/bilheteria/caixa'
    | '/bilheteria/impressao'
    | '/bilheteria/retirada'
    | '/e/$slug'
    | '/f/$codigo'
    | '/p/$acesso'
    | '/termos/$slug'
    | '/admin/'
    | '/bilheteria/'
    | '/admin/eventos/$eventoId'
    | '/bilheteria/familia/$familiaId'
    | '/e/$slug/$sessaoId'
    | '/f/$codigo/$sessaoId'
    | '/admin/eventos/'
    | '/admin/locais/'
    | '/e/$slug/'
    | '/f/$codigo/'
    | '/admin/eventos/$eventoId/adicionais'
    | '/admin/eventos/$eventoId/conteudos'
    | '/admin/eventos/$eventoId/elenco'
    | '/admin/eventos/$eventoId/envio'
    | '/admin/eventos/$eventoId/precos'
    | '/admin/eventos/$eventoId/sessoes'
    | '/admin/eventos/$eventoId/visao-geral'
    | '/api/pagarme/webhook/$segredo'
    | '/f/$codigo/pagamento/$acesso'
    | '/f/$codigo/pedido/$acesso'
    | '/admin/eventos/$eventoId/'
    | '/admin/locais/$localId/mapas/$mapaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/privacidade'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/bilheteria/avulsa'
    | '/bilheteria/caixa'
    | '/bilheteria/impressao'
    | '/bilheteria/retirada'
    | '/p/$acesso'
    | '/termos/$slug'
    | '/admin'
    | '/bilheteria'
    | '/bilheteria/familia/$familiaId'
    | '/e/$slug/$sessaoId'
    | '/f/$codigo/$sessaoId'
    | '/admin/eventos'
    | '/admin/locais'
    | '/e/$slug'
    | '/f/$codigo'
    | '/admin/eventos/$eventoId/adicionais'
    | '/admin/eventos/$eventoId/conteudos'
    | '/admin/eventos/$eventoId/elenco'
    | '/admin/eventos/$eventoId/envio'
    | '/admin/eventos/$eventoId/precos'
    | '/admin/eventos/$eventoId/sessoes'
    | '/admin/eventos/$eventoId/visao-geral'
    | '/api/pagarme/webhook/$segredo'
    | '/f/$codigo/pagamento/$acesso'
    | '/f/$codigo/pedido/$acesso'
    | '/admin/eventos/$eventoId'
    | '/admin/locais/$localId/mapas/$mapaId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bilheteria'
    | '/entrar'
    | '/privacidade'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/equipe'
    | '/bilheteria/avulsa'
    | '/bilheteria/caixa'
    | '/bilheteria/impressao'
    | '/bilheteria/retirada'
    | '/e/$slug'
    | '/f/$codigo'
    | '/p/$acesso'
    | '/termos/$slug'
    | '/admin/'
    | '/bilheteria/'
    | '/admin/eventos/$eventoId'
    | '/bilheteria/familia/$familiaId'
    | '/e/$slug/$sessaoId'
    | '/f/$codigo/$sessaoId'
    | '/admin/eventos/'
    | '/admin/locais/'
    | '/e/$slug/'
    | '/f/$codigo/'
    | '/admin/eventos/$eventoId/adicionais'
    | '/admin/eventos/$eventoId/conteudos'
    | '/admin/eventos/$eventoId/elenco'
    | '/admin/eventos/$eventoId/envio'
    | '/admin/eventos/$eventoId/precos'
    | '/admin/eventos/$eventoId/sessoes'
    | '/admin/eventos/$eventoId/visao-geral'
    | '/api/pagarme/webhook/$segredo'
    | '/f/$codigo/pagamento/$acesso'
    | '/f/$codigo/pedido/$acesso'
    | '/admin/eventos/$eventoId/'
    | '/admin/locais/$localId/mapas/$mapaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BilheteriaRoute: typeof BilheteriaRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ESlugRoute: typeof ESlugRouteWithChildren
  FCodigoRoute: typeof FCodigoRouteWithChildren
  PAcessoRoute: typeof PAcessoRoute
  TermosSlugRoute: typeof TermosSlugRoute
  ApiPagarmeWebhookSegredoRoute: typeof ApiPagarmeWebhookSegredoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilheteria': {
      id: '/bilheteria'
      path: '/bilheteria'
      fullPath: '/bilheteria'
      preLoaderRoute: typeof BilheteriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipe': {
      id: '/admin/equipe'
      path: '/equipe'
      fullPath: '/admin/equipe'
      preLoaderRoute: typeof AdminEquipeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bilheteria/': {
      id: '/bilheteria/'
      path: '/'
      fullPath: '/bilheteria/'
      preLoaderRoute: typeof BilheteriaIndexRouteImport
      parentRoute: typeof BilheteriaRoute
    }
    '/bilheteria/avulsa': {
      id: '/bilheteria/avulsa'
      path: '/avulsa'
      fullPath: '/bilheteria/avulsa'
      preLoaderRoute: typeof BilheteriaAvulsaRouteImport
      parentRoute: typeof BilheteriaRoute
    }
    '/bilheteria/caixa': {
      id: '/bilheteria/caixa'
      path: '/caixa'
      fullPath: '/bilheteria/caixa'
      preLoaderRoute: typeof BilheteriaCaixaRouteImport
      parentRoute: typeof BilheteriaRoute
    }
    '/bilheteria/impressao': {
      id: '/bilheteria/impressao'
      path: '/impressao'
      fullPath: '/bilheteria/impressao'
      preLoaderRoute: typeof BilheteriaImpressaoRouteImport
      parentRoute: typeof BilheteriaRoute
    }
    '/bilheteria/retirada': {
      id: '/bilheteria/retirada'
      path: '/retirada'
      fullPath: '/bilheteria/retirada'
      preLoaderRoute: typeof BilheteriaRetiradaRouteImport
      parentRoute: typeof BilheteriaRoute
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$codigo': {
      id: '/f/$codigo'
      path: '/f/$codigo'
      fullPath: '/f/$codigo'
      preLoaderRoute: typeof FCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$acesso': {
      id: '/p/$acesso'
      path: '/p/$acesso'
      fullPath: '/p/$acesso'
      preLoaderRoute: typeof PAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos/$slug': {
      id: '/termos/$slug'
      path: '/termos/$slug'
      fullPath: '/termos/$slug'
      preLoaderRoute: typeof TermosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/eventos/': {
      id: '/admin/eventos/'
      path: '/eventos'
      fullPath: '/admin/eventos/'
      preLoaderRoute: typeof AdminEventosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos/$eventoId': {
      id: '/admin/eventos/$eventoId'
      path: '/eventos/$eventoId'
      fullPath: '/admin/eventos/$eventoId'
      preLoaderRoute: typeof AdminEventosEventoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locais/': {
      id: '/admin/locais/'
      path: '/locais'
      fullPath: '/admin/locais/'
      preLoaderRoute: typeof AdminLocaisIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bilheteria/familia/$familiaId': {
      id: '/bilheteria/familia/$familiaId'
      path: '/familia/$familiaId'
      fullPath: '/bilheteria/familia/$familiaId'
      preLoaderRoute: typeof BilheteriaFamiliaFamiliaIdRouteImport
      parentRoute: typeof BilheteriaRoute
    }
    '/e/$slug/': {
      id: '/e/$slug/'
      path: '/'
      fullPath: '/e/$slug/'
      preLoaderRoute: typeof ESlugIndexRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/e/$slug/$sessaoId': {
      id: '/e/$slug/$sessaoId'
      path: '/$sessaoId'
      fullPath: '/e/$slug/$sessaoId'
      preLoaderRoute: typeof ESlugSessaoIdRouteImport
      parentRoute: typeof ESlugRoute
    }
    '/f/$codigo/': {
      id: '/f/$codigo/'
      path: '/'
      fullPath: '/f/$codigo/'
      preLoaderRoute: typeof FCodigoIndexRouteImport
      parentRoute: typeof FCodigoRoute
    }
    '/f/$codigo/$sessaoId': {
      id: '/f/$codigo/$sessaoId'
      path: '/$sessaoId'
      fullPath: '/f/$codigo/$sessaoId'
      preLoaderRoute: typeof FCodigoSessaoIdRouteImport
      parentRoute: typeof FCodigoRoute
    }
    '/admin/eventos/$eventoId/': {
      id: '/admin/eventos/$eventoId/'
      path: '/'
      fullPath: '/admin/eventos/$eventoId/'
      preLoaderRoute: typeof AdminEventosEventoIdIndexRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/admin/eventos/$eventoId/adicionais': {
      id: '/admin/eventos/$eventoId/adicionais'
      path: '/adicionais'
      fullPath: '/admin/eventos/$eventoId/adicionais'
      preLoaderRoute: typeof AdminEventosEventoIdAdicionaisRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/admin/eventos/$eventoId/conteudos': {
      id: '/admin/eventos/$eventoId/conteudos'
      path: '/conteudos'
      fullPath: '/admin/eventos/$eventoId/conteudos'
      preLoaderRoute: typeof AdminEventosEventoIdConteudosRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/admin/eventos/$eventoId/elenco': {
      id: '/admin/eventos/$eventoId/elenco'
      path: '/elenco'
      fullPath: '/admin/eventos/$eventoId/elenco'
      preLoaderRoute: typeof AdminEventosEventoIdElencoRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/admin/eventos/$eventoId/envio': {
      id: '/admin/eventos/$eventoId/envio'
      path: '/envio'
      fullPath: '/admin/eventos/$eventoId/envio'
      preLoaderRoute: typeof AdminEventosEventoIdEnvioRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/admin/eventos/$eventoId/precos': {
      id: '/admin/eventos/$eventoId/precos'
      path: '/precos'
      fullPath: '/admin/eventos/$eventoId/precos'
      preLoaderRoute: typeof AdminEventosEventoIdPrecosRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/admin/eventos/$eventoId/sessoes': {
      id: '/admin/eventos/$eventoId/sessoes'
      path: '/sessoes'
      fullPath: '/admin/eventos/$eventoId/sessoes'
      preLoaderRoute: typeof AdminEventosEventoIdSessoesRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/admin/eventos/$eventoId/visao-geral': {
      id: '/admin/eventos/$eventoId/visao-geral'
      path: '/visao-geral'
      fullPath: '/admin/eventos/$eventoId/visao-geral'
      preLoaderRoute: typeof AdminEventosEventoIdVisaoGeralRouteImport
      parentRoute: typeof AdminEventosEventoIdRoute
    }
    '/api/pagarme/webhook/$segredo': {
      id: '/api/pagarme/webhook/$segredo'
      path: '/api/pagarme/webhook/$segredo'
      fullPath: '/api/pagarme/webhook/$segredo'
      preLoaderRoute: typeof ApiPagarmeWebhookSegredoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$codigo/pagamento/$acesso': {
      id: '/f/$codigo/pagamento/$acesso'
      path: '/pagamento/$acesso'
      fullPath: '/f/$codigo/pagamento/$acesso'
      preLoaderRoute: typeof FCodigoPagamentoAcessoRouteImport
      parentRoute: typeof FCodigoRoute
    }
    '/f/$codigo/pedido/$acesso': {
      id: '/f/$codigo/pedido/$acesso'
      path: '/pedido/$acesso'
      fullPath: '/f/$codigo/pedido/$acesso'
      preLoaderRoute: typeof FCodigoPedidoAcessoRouteImport
      parentRoute: typeof FCodigoRoute
    }
    '/admin/locais/$localId/mapas/$mapaId': {
      id: '/admin/locais/$localId/mapas/$mapaId'
      path: '/locais/$localId/mapas/$mapaId'
      fullPath: '/admin/locais/$localId/mapas/$mapaId'
      preLoaderRoute: typeof AdminLocaisLocalIdMapasMapaIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminEventosEventoIdRouteChildren {
  AdminEventosEventoIdAdicionaisRoute: typeof AdminEventosEventoIdAdicionaisRoute
  AdminEventosEventoIdConteudosRoute: typeof AdminEventosEventoIdConteudosRoute
  AdminEventosEventoIdElencoRoute: typeof AdminEventosEventoIdElencoRoute
  AdminEventosEventoIdEnvioRoute: typeof AdminEventosEventoIdEnvioRoute
  AdminEventosEventoIdPrecosRoute: typeof AdminEventosEventoIdPrecosRoute
  AdminEventosEventoIdSessoesRoute: typeof AdminEventosEventoIdSessoesRoute
  AdminEventosEventoIdVisaoGeralRoute: typeof AdminEventosEventoIdVisaoGeralRoute
  AdminEventosEventoIdIndexRoute: typeof AdminEventosEventoIdIndexRoute
}

const AdminEventosEventoIdRouteChildren: AdminEventosEventoIdRouteChildren = {
  AdminEventosEventoIdAdicionaisRoute: AdminEventosEventoIdAdicionaisRoute,
  AdminEventosEventoIdConteudosRoute: AdminEventosEventoIdConteudosRoute,
  AdminEventosEventoIdElencoRoute: AdminEventosEventoIdElencoRoute,
  AdminEventosEventoIdEnvioRoute: AdminEventosEventoIdEnvioRoute,
  AdminEventosEventoIdPrecosRoute: AdminEventosEventoIdPrecosRoute,
  AdminEventosEventoIdSessoesRoute: AdminEventosEventoIdSessoesRoute,
  AdminEventosEventoIdVisaoGeralRoute: AdminEventosEventoIdVisaoGeralRoute,
  AdminEventosEventoIdIndexRoute: AdminEventosEventoIdIndexRoute,
}

const AdminEventosEventoIdRouteWithChildren =
  AdminEventosEventoIdRoute._addFileChildren(AdminEventosEventoIdRouteChildren)

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminEquipeRoute: typeof AdminEquipeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventosEventoIdRoute: typeof AdminEventosEventoIdRouteWithChildren
  AdminEventosIndexRoute: typeof AdminEventosIndexRoute
  AdminLocaisIndexRoute: typeof AdminLocaisIndexRoute
  AdminLocaisLocalIdMapasMapaIdRoute: typeof AdminLocaisLocalIdMapasMapaIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminEquipeRoute: AdminEquipeRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventosEventoIdRoute: AdminEventosEventoIdRouteWithChildren,
  AdminEventosIndexRoute: AdminEventosIndexRoute,
  AdminLocaisIndexRoute: AdminLocaisIndexRoute,
  AdminLocaisLocalIdMapasMapaIdRoute: AdminLocaisLocalIdMapasMapaIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BilheteriaRouteChildren {
  BilheteriaAvulsaRoute: typeof BilheteriaAvulsaRoute
  BilheteriaCaixaRoute: typeof BilheteriaCaixaRoute
  BilheteriaImpressaoRoute: typeof BilheteriaImpressaoRoute
  BilheteriaRetiradaRoute: typeof BilheteriaRetiradaRoute
  BilheteriaIndexRoute: typeof BilheteriaIndexRoute
  BilheteriaFamiliaFamiliaIdRoute: typeof BilheteriaFamiliaFamiliaIdRoute
}

const BilheteriaRouteChildren: BilheteriaRouteChildren = {
  BilheteriaAvulsaRoute: BilheteriaAvulsaRoute,
  BilheteriaCaixaRoute: BilheteriaCaixaRoute,
  BilheteriaImpressaoRoute: BilheteriaImpressaoRoute,
  BilheteriaRetiradaRoute: BilheteriaRetiradaRoute,
  BilheteriaIndexRoute: BilheteriaIndexRoute,
  BilheteriaFamiliaFamiliaIdRoute: BilheteriaFamiliaFamiliaIdRoute,
}

const BilheteriaRouteWithChildren = BilheteriaRoute._addFileChildren(
  BilheteriaRouteChildren,
)

interface ESlugRouteChildren {
  ESlugSessaoIdRoute: typeof ESlugSessaoIdRoute
  ESlugIndexRoute: typeof ESlugIndexRoute
}

const ESlugRouteChildren: ESlugRouteChildren = {
  ESlugSessaoIdRoute: ESlugSessaoIdRoute,
  ESlugIndexRoute: ESlugIndexRoute,
}

const ESlugRouteWithChildren = ESlugRoute._addFileChildren(ESlugRouteChildren)

interface FCodigoRouteChildren {
  FCodigoSessaoIdRoute: typeof FCodigoSessaoIdRoute
  FCodigoIndexRoute: typeof FCodigoIndexRoute
  FCodigoPagamentoAcessoRoute: typeof FCodigoPagamentoAcessoRoute
  FCodigoPedidoAcessoRoute: typeof FCodigoPedidoAcessoRoute
}

const FCodigoRouteChildren: FCodigoRouteChildren = {
  FCodigoSessaoIdRoute: FCodigoSessaoIdRoute,
  FCodigoIndexRoute: FCodigoIndexRoute,
  FCodigoPagamentoAcessoRoute: FCodigoPagamentoAcessoRoute,
  FCodigoPedidoAcessoRoute: FCodigoPedidoAcessoRoute,
}

const FCodigoRouteWithChildren =
  FCodigoRoute._addFileChildren(FCodigoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BilheteriaRoute: BilheteriaRouteWithChildren,
  EntrarRoute: EntrarRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ESlugRoute: ESlugRouteWithChildren,
  FCodigoRoute: FCodigoRouteWithChildren,
  PAcessoRoute: PAcessoRoute,
  TermosSlugRoute: TermosSlugRoute,
  ApiPagarmeWebhookSegredoRoute: ApiPagarmeWebhookSegredoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
